import type { CarrierId } from '../generated/catalog.js';

export interface TrackingLinkCase {
  carrier: CarrierId;
  provider?: string;
  /** Synthetic and validly shaped; never a real parcel. */
  number: string;
  /** Final address after redirects. */
  route: RegExp;
  /** Wording only the carrier's tracker shows. */
  marker: RegExp;
  /** An observed shipment-absence response on the working tracker route. */
  shipmentNotFound?: { status: 404 | 410; marker: RegExp };
  /** A visible tracker rendered inside an open shadow root. */
  shadowHost?: string;
  /** Extra hydration time for a tracker whose form loads in a separate client chunk. */
  renderTimeoutMs?: number;
  /**
   * How the page proves it received the number. By default the number must be
   * looked up, displayed or prefilled. `notFound` is the carrier's specific
   * answer to an unknown number when that answer clears the number from the
   * page; `none` marks a link that carries no number or one the site ignores.
   */
  forwarding?: { notFound: RegExp } | 'none';
}

// Rendered pages behind the links the UI shows, checked daily by
// trackingLinks.live.test.ts. Routes and markers were read from the live pages,
// independently of the generated link templates, so a template that drifts
// fails here instead of passing against itself.
export const trackingLinkCases: TrackingLinkCase[] = [
  { carrier: 'dhl-express', number: '9876000046',
    route: /^https:\/\/mydhl\.express\.dhl\/gb\/en\/tracking\.html/,
    marker: /Tracking Results|No result found for your DHL query|Not found/i, renderTimeoutMs: 20_000 },
  { carrier: 'mrw', number: '99000Z000001',
    route: /^https:\/\/www\.mrw\.es\/seguimiento(?:\/|$)/,
    marker: /Seguimiento de envíos|Seguimiento de envios|Número de envío|Nº de envío/i,
    forwarding: 'none' },
  { carrier: 'parcelforce', number: 'CP000000005GB',
    route: /^https:\/\/www\.royalmail\.com\/track-your-item(?:#|$)/,
    marker: /Track your item|Tracking number|Enter your.*number/i, renderTimeoutMs: 20_000 },
  { carrier: 'the-courier-guy', number: 'TESTA1',
    route: /^https:\/\/portal\.thecourierguy\.co\.za\/track/,
    marker: /Track your parcel|Waybill not found|Enter tracking reference/i },
  { carrier: 'the-courier-guy', number: 'LD-000001',
    route: /^https:\/\/portal\.thecourierguy\.co\.za\/track/,
    marker: /Track your parcel|Waybill not found|Enter tracking reference/i },
  { carrier: 'bring-posten', number: 'RR000000005NO',
    route: /^https:\/\/sporing\.bring\.no\/sporing\//,
    marker: /Track.*item|Tracking number|didn.t find a shipment|Sporingsnummer|Spor pakken|vi fant ingen sending/i,
    shipmentNotFound: { status: 404, marker: /Sorry, we didn.t find a shipment associated with RR000000005NO/ } },
  { carrier: 'estafeta', number: '9000000001',
    route: /^https:\/\/cs\.estafeta\.com\/es\/Tracking\/searchByGet/,
    marker: /Código de rastreo|Número de guía|no se encontró información|Rastrear Envío/i,
    forwarding: { notFound: /Lo sentimos, no se encontró información/i } },
  { carrier: 'estafeta', number: '900000000001A000000002',
    route: /^https:\/\/cs\.estafeta\.com\/es\/Tracking\/searchByGet/,
    marker: /Código de rastreo|Número de guía|no se encontró información|Rastrear Envío/i,
    forwarding: { notFound: /Lo sentimos, no se encontró información/i } },
  { carrier: 'nacex', number: '9900/99000002',
    route: /^https:\/\/www\.nacex\.es\/seguimientoFormularioExterno\.do(?:\?|$)/,
    marker: /Formulario de Seguimiento|Formulaire de Suivi|Track and trace form/,
    forwarding: { notFound: /No existe ningún albarán introducido en el sistema cumpliendo los criterios especificados|Il n.y a aucun bordereau introduit dans le système correspondant aux critères indiqués|There are no delivery notes entered into the system that comply with the specified criteria/ } },
  { carrier: 'seur', number: '9900002',
    route: /^https:\/\/www\.seur\.com\/miseur\/mis-envios(?:\?|$)/,
    marker: /Seguimiento de envíos|Mis envíos|localizador|shipment|IDENTIFIER|Tracking|NÚMERO DE ENVÍO/i, renderTimeoutMs: 20_000 },
  { carrier: 'brt', number: '99000000000002',
    route: /^https:\/\/vas\.brt\.it\/vas\/sped_det_new\.htm(?:\?|$)/,
    marker: /Errori riscontrati|BRTcode|Parcel Label number .* not found/i },
  { carrier: 'ukrposhta', number: 'EE000000005UA',
    route: /^https:\/\/track\.ukrposhta\.ua\/en\//,
    marker: /Track.*parcel|Tracking|Shipment not found|barcode/i, renderTimeoutMs: 20_000 },
  { carrier: 'landmark-global', number: 'LTN000000009',
    route: /^https:\/\/track\.landmarkglobal\.com\//,
    marker: /Track your shipment|couldn't find a match/i },
  { carrier: 'gofo', number: 'GFUS00000000000000',
    route: /^https:\/\/www\.gofo\.com\/us\/track/,
    marker: /Track Your Package|Enter your Tracking Number/i },
  { carrier: 'ecoscooting', number: '000000000000000000',
    route: /^https:\/\/ecoscooting\.com\/tracking\//,
    marker: /Enter tracking number|No data found/i },
  { carrier: 'ecoscooting', number: 'CNPRT00000000000000000001',
    route: /^https:\/\/ecoscooting\.com\/tracking\//,
    marker: /Enter tracking number|No data found/i },
  { carrier: 'canpar', number: 'C000000000000000000001',
    route: /^https:\/\/www\.canpar\.com\/en\/tracking\/track\.htm/,
    marker: /Track.*package|Package tracking|Track.*shipment|Enter.*barcode/i },
  { carrier: 'ninja-van', number: 'NLMYA00000000',
    route: /^https:\/\/www\.ninjavan\.co\/en-my\/tracking(?:\?|$)/,
    marker: /Track and trace your parcel|Enter parcel tracking ID|Track parcel/i },
  { carrier: 'correos-chile', number: 'SX000000005CL',
    route: /^https:\/\/www\.correos\.cl\/seguimiento-en-linea(?:\?|$)/,
    marker: /Seguimiento en línea|Envíos y Seguimiento de Paquetes/i,
    forwarding: 'none' },
  { carrier: 'correos-express', number: '9900000000000002',
    route: /^https:\/\/s\.correosexpress\.com\//,
    marker: /Localiza tu envío|Sigue tu envío/i, forwarding: 'none' },
  { carrier: 'nz-post', number: '00000000000000000001',
    route: /^https:\/\/www\.nzpost\.co\.nz\/tools\/tracking/,
    marker: /Tracking number|Track.*parcel|Tracking reference/i },
  { carrier: 'poczta-polska', number: '00000000000000000001',
    route: /^https:\/\/emonitoring\.poczta-polska\.pl\//,
    marker: /Tracking|Enter.*number|Search/i },
  { carrier: 'ctt-express', number: '0000000000000000000001',
    route: /^https:\/\/shipping-tracking\.production\.cloud2\.cttexpress\.com\//,
    marker: /Número de seguimiento|No hemos localizado el número de envío/i },
  // An unknown reference refreshes to the not-located page after 10 s.
  { carrier: 'tipsa', number: '0990010990010000000017',
    route: /^https:\/\/aplicaciones\.tip-sa\.com\/cliente\/(?:datos_env\.php\?|error_env\.html$)/,
    marker: /ENVIO NO LOCALIZADO/i, renderTimeoutMs: 20_000,
    forwarding: { notFound: /ENVIO NO LOCALIZADO/i } },
  { carrier: 'uniuni', number: 'UUS0000000000000000',
    route: /^https:\/\/www\.uniuni\.com\/tracking\//,
    marker: /Track your UniUni Package/i },
  { carrier: 'uniuni', number: 'UUSC000000000001',
    route: /^https:\/\/www\.uniuni\.com\/tracking\//,
    marker: /Track your UniUni Package/i },
  { carrier: 'speedx', number: 'SPXLAX000000000000000001',
    route: /^https:\/\/tracking\.speedx\.io\/SPXLAX000000000000000001$/,
    marker: /No tracking information for/i },
  { carrier: 'bpost', number: '000000000000000000000001',
    route: /^https:\/\/track\.bpost\.cloud\//,
    marker: /Track|barcode|postcode|postal code|Suivi|Code-barres/i, forwarding: 'none' },
  { carrier: 'purolator', number: '100000000001',
    route: /^https:\/\/www\.purolator\.com\/en\/shipping\/tracker/,
    marker: /Track.*shipment|Tracking|Tracking number/i },
  { carrier: 'yto', number: 'YT0000000000001',
    route: /^https:\/\/www\.yto\.net\.cn\/ytoExpress\/waybill\/search/,
    marker: /运单|快递|Waybill|Tracking/i, forwarding: 'none' },
  { carrier: 'sto', number: '777000000000001',
    route: /^https:\/\/www\.sto\.cn\//,
    marker: /运单|单号|查询/i, forwarding: 'none' },
  { carrier: 'correios-br', number: 'AA000000005BR',
    route: /^https:\/\/rastreamento\.correios\.com\.br\/app\/index\.php/,
    marker: /Rastreamento|Objeto|Código|Captcha/i },
  // The page stays blank until its script bundles arrive from China: often 20 s, sometimes over 40 s.
  { carrier: 'yunda', number: '0000000000001',
    route: /^https:\/\/web\.yundaex\.com\/infoInquiry/,
    marker: /快件查询|请输入运单号/i, renderTimeoutMs: 60_000 },
  { carrier: 'postnord', number: 'RR000000005SE',
    route: /^https:\/\/tracking\.postnord\.com\/en\//,
    marker: /Track.*shipment|Tracking|shipment.*found/i, shadowHost: 'pn-widget' },
  { carrier: 'yunexpress', number: 'YT0000000000000001',
    route: /^https:\/\/www\.yuntrack\.com\/parcelTracking\?id=/,
    marker: /Tracking|Track.*parcel|Tracking Number/i },
  { carrier: 'austrian-post', number: '1000000000000000000001',
    route: /^https:\/\/www\.post\.at\/en\/s\/track-and-trace-search/,
    marker: /Track.*Trace|Track a shipment|Shipment tracking|tracking number/i, forwarding: 'none' },
  { carrier: 'tnt', number: '123456784',
    route: /^https:\/\/www\.tnt\.com\/express\/en_gb\/site\/shipping-tools\/tracking\.html\?/,
    marker: /Track your shipment|Consignment note/i },
  { carrier: 'ontrac', number: '1LS0000000000001',
    route: /^https:\/\/www\.ontrac\.com\/tracking\//,
    marker: /Track.*package|Tracking|tracking number/i },
  { carrier: 'blue-dart', number: '00000000001',
    route: /^https:\/\/www\.bluedart\.com\/trackdartresultthirdparty/,
    marker: /TrackDart|Tracking Details/i,
    forwarding: { notFound: /There is no information on the Waybill\/Reference Number\/Order Number currently/i } },
  { carrier: 'delhivery', number: '0000000000001',
    route: /^https:\/\/www\.delhivery\.com\/tracking/,
    marker: /Track Order|AWB|Track your shipment/i, forwarding: 'none' },
  { carrier: 'aramex', number: '999999999999',
    route: /^https:\/\/www\.aramex\.com\/us\/en\/track\/shipments/,
    marker: /Track|tracking number/i,
    forwarding: { notFound: /No results found with current selection/i } },
  { carrier: 'four-px', number: '4PX0000000000001CN',
    route: /^https:\/\/track\.4px\.com\//,
    marker: /Track|Tracking|tracking number/i },
  { carrier: 'singapore-post', number: 'RR000000005SG',
    route: /^https:\/\/www\.singpost\.com\/track-items/,
    marker: /Track.*items|Track.*shipment|Tracking Number/i },
  { carrier: 'hongkong-post', number: 'RR000000005HK',
    route: /^https:\/\/webapp\.hongkongpost\.hk\/en\/mail_tracking2\/index\.html/,
    marker: /Track and Trace|Enter The Tracking Number|Recently tracked items/i,
    forwarding: 'none' },
  { carrier: 'korea-post', number: 'EE000000005KR',
    route: /^https:\/\/trace\.epost\.go\.kr\/xtts\//,
    marker: /Track.*Trace|Tracking|Item Number|Delivery Status/i },
  { carrier: 'yamato', number: '123456789012',
    route: /^https:\/\/toi\.kuronekoyamato\.co\.jp\/cgi-bin\/tneko/,
    marker: /荷物お問い合わせ|送り状番号|Tracking/i, forwarding: 'none' },
  { carrier: 'yanwen', number: 'UK000000005YP',
    route: /^https:\/\/track\.yw56\.com\.cn\/en\/index/,
    marker: /Tracking|Tracking number|Track/i, forwarding: 'none' },
  { carrier: 'sf-express', number: 'SF0000000000001',
    route: /^https:\/\/htm\.sf-express\.com\/tw\/en\/dynamic_function\/waybill\/#search\/bill-number\//,
    marker: /Track.*Trace|Shipment|Waybill/i },
  { carrier: 'swiss-post', number: '989999999999999999',
    route: /^https:\/\/service\.post\.ch\/ekp-web\/ui\//,
    marker: /Meine Sendungen|My consignments|Mes envois|Sendungsnummer/ },
  { carrier: 'postlogistics', number: '000000000000000000',
    route: /^https:\/\/apv\.swisspost-cargo\.com\/public\/trackandtrace\//,
    marker: /Sendungsnummer\/Referenz|Keine Daten gefunden|TRACK&TRACE/i },
  { carrier: 'swiss-post-cargo', number: 'CODEXINVALID20260831',
    route: /^https:\/\/apv\.swisspost-cargo\.com\/public\/trackandtrace\//,
    marker: /Sendungsnummer\/Referenz|Keine Daten gefunden|TRACK&TRACE/i },
  { carrier: 'quickpac', number: '440000000000000001',
    route: /^https:\/\/tracking\.app\.planzer\.ch\/delivery\/info\?/,
    marker: /Mes envois|Meine Sendungen|My shipments|aucune information|keine Informationen/i },
  { carrier: 'la-poste', number: 'AB12345678901',
    route: /^https:\/\/www\.laposte\.fr\/outils\/suivre-vos-envois(?:\?|$)/,
    marker: /suivre une lettre ou un colis|suivre un envoi|suivi de votre|numéro de suivi/i },
  { carrier: 'chronopost', number: 'XY000000005FR',
    route: /^https:\/\/www\.chronopost\.fr\/tracking-no-cms\/suivi-page\?/,
    marker: /Suivez votre colis|Informations concernant votre envoi/i },
  { carrier: 'dpd', number: '09999999999999',
    route: /^https:\/\/www\.dpdgroup\.com\/ch\/mydpd\/my-parcels\/incoming\?/,
    marker: /parcel number|Paketnummer|numéro de colis|my parcels/i,
    // The server-rendered unknown-number view deliberately clears the input.
    forwarding: { notFound: /The parcel you have chosen has not been assigned to your account/ } },
  // Cloudflare challenges automated browsers; kept so the gap stays visible.
  { carrier: 'dpd-fr', number: '000000000000',
    route: /^https:\/\/trace\.dpd\.fr\/fr\/trace\//,
    marker: /suivi|colis|parcel/i },
  { carrier: 'unknown', number: 'ZZ000000000ZZ',
    route: /^https:\/\/t\.17track\.net\/en(?:[?#]|$)/,
    marker: /TRACK|SUIVRE|Tracking Information/ },
  { carrier: 'dhl', number: '00340439999999999999',
    route: /^https:\/\/www\.dhl\.de\/en\/privatkunden\/dhl-sendungsverfolgung\.html\?/,
    marker: /shipment number|track shipment/i },
  { carrier: 'dhl-ecommerce-nl', number: 'JVGL09999999000000000000',
    route: /^https:\/\/my\.dhlecommerce\.nl\/home\/tracktrace\/JVGL09999999000000000000/,
    marker: /Track & Trace|track your parcel|parcel/i },
  { carrier: 'dhl-ecommerce-uk', number: '99990000000000',
    route: /^https:\/\/track\.dhlecommerce\.co\.uk\/\?con=99990000000000/,
    marker: /track another parcel|shipment number/i },
  { carrier: 'dhl-ecommerce-es', number: '2800000007',
    route: /^https:\/\/clientesparcel\.dhl\.es\/LiveTracking\//,
    marker: /shipment|tracking|env[ií]o/i },
  { carrier: 'dhl-ecommerce-pl', number: '29999999990',
    // The portal moves an unknown number from /tracking to its search form.
    route: /^https:\/\/mojdhl\.pl\/(?:tracking\?paczki=29999999990|sprawdz)/,
    marker: /parcel|shipment|przesy[łl]k/i },
  { carrier: 'dhl-ecommerce', number: 'GM0000000000000000',
    route: /^https:\/\/www\.dhl\.com\/ch-en\/home\/tracking\.html\?/,
    marker: /tracking number|track your shipment/i },
  { carrier: 'mondial-relay', number: '00000000',
    route: /^https:\/\/www\.mondialrelay\.fr\/suivi-de-colis\//,
    marker: /suivi de colis|numéro de colis/i },
  { carrier: 'mondial-relay', provider: 'ParcelsApp', number: '00000000',
    route: /^https:\/\/parcelsapp\.com\/en\/tracking\//,
    marker: /tracking number|track package|tracking information/i },
  { carrier: 'relais-colis', number: '0000000000',
    route: /^https:\/\/www\.relaiscolis\.com\/colis\/suivre\?/,
    marker: /Suivre mon colis/i },
  { carrier: 'gls-ch', number: '88888888888',
    route: /^https:\/\/gls-group\.eu\/EU\/en\/parcel-tracking\?/,
    marker: /Parcel tracking|Track your parcel/i },
  // moncolis.gls-france.com now forwards to the group tracker.
  { carrier: 'gls-fr', number: '00ZZ00Z0',
    route: /^https:\/\/(?:moncolis\.gls-france\.com\/|gls-group\.eu\/GROUP\/[a-z]{2}\/parcel-tracking\?)/,
    marker: /Parcel tracking|Track your parcel|Suivi/i },
  { carrier: 'gls-de', number: '00000000000',
    route: /^https:\/\/(?:gls-group\.eu\/DE\/de\/paketverfolgung|www\.gls-pakete\.de\/(?:reach-)?sendungsverfolgung)/,
    marker: /Paketnummer|Sendungsverfolgung|Track ID/i },
  { carrier: 'ups', number: '1Z0000000000000000',
    route: /^https:\/\/(?:www\.)?ups\.com\/track(?:[/?]|$)/,
    marker: /tracking number|numéro de suivi|track a package/i },
  { carrier: 'fedex', number: '999999999999',
    route: /^https:\/\/www\.fedex\.com\/(?:fedextrack|wtrk\/track)\//,
    marker: /FedEx ® Tracking|Track Another Shipment|can.t find that tracking number/i },
  { carrier: 'amazon-shipping', number: 'FR0000000000',
    route: /^https:\/\/track\.amazon\.fr\/tracking\//,
    marker: /Numéro de suivi|Tracking number|Suivre un colis/i },
  // Amazon Logistics parcels are tracked from the signed-in order history.
  { carrier: 'amazon-logistics', number: 'TBA000000000000',
    route: /^https:\/\/www\.amazon\.com\/(?:ap\/signin|gp\/your-account\/order-history|your-orders)/,
    marker: /Sign in|Your Orders/i, forwarding: 'none' },
  { carrier: 'geodis', number: '1G0000000000',
    route: /^https:\/\/espace-client\.geodis\.com\/services\/destinataires\//,
    marker: /Suivre mon envoi|Numéro de suivi/i },
  // Colisweb ignores ?value= since its search became an in-page request.
  { carrier: 'colisweb', number: '99999999',
    route: /^https:\/\/www\.colisweb\.com\/suivi-livraison/,
    marker: /Suivi de votre livraison|Suivre ma livraison/i, forwarding: 'none' },
  { carrier: 'c-chez-vous', number: 'ZZZZ00000Z',
    route: /^https:\/\/www\.cchezvous\.fr\/suivi-colis/,
    marker: /Suivre ma livraison/i,
    forwarding: { notFound: /La commande est introuvable/ } },
  { carrier: 'heppner', number: '00000000',
    route: /^https:\/\/www\.heppner-group\.com\/(?:en\/consignee-track-your-order|destinataire-suivez-votre-marchandise)\//,
    marker: /track your order|suivez votre marchandise/i, forwarding: 'none' },
  { carrier: 'ciblex', number: '12345678901234',
    route: /^https:\/\/secure\.extranet\.ciblex\.fr\/extranet\/client\/corps\.php\?/,
    marker: /SUIVI DE VOS COLIS|SUIVI COLIS/i },
  { carrier: 'ciblex', number: '000000000000000000000001',
    route: /^https:\/\/secure\.extranet\.ciblex\.fr\/extranet\/client\/corps\.php\?/,
    marker: /SUIVI DE VOS COLIS|SUIVI COLIS/i },
  { carrier: 'paack', number: 'EXCHANGE000001D',
    route: /^https:\/\/mydeliveries\.paack\.app\/tracking\?/,
    marker: /Track your order|Track My Order|Order number/i },
  { carrier: 'asendia', number: 'ASE00000000',
    route: /^https:\/\/track\.asendia\.com\/track\//,
    marker: /Tracking Portal|Track here/i },
  { carrier: 'hermes', number: '12345678',
    route: /^https:\/\/myhes\.de\//,
    marker: /Sendungsverfolgung/i, forwarding: 'none' },
  { carrier: 'hermes-de', number: '00000000000000',
    route: /^https:\/\/www\.myhermes\.de\/empfangen\/sendungsverfolgung\//,
    marker: /Sendungsverfolgung|Sendungsinformation/i },
  { carrier: 'inpost', number: '000000000000000000000000',
    route: /^https:\/\/inpost\.pl\/sledzenie-przesylek/,
    marker: /Śledzenie paczki|Śledź paczkę|numery paczek/i, forwarding: 'none' },
  { carrier: 'posti', number: 'CW000000000FR',
    route: /^https:\/\/www\.posti\.fi\/en\/tracking\//,
    marker: /Track item|Parcel tracking|Search by item ID/i },
  { carrier: 'packeta', number: 'Z0000000000',
    route: /^https:\/\/tracking\.packeta\.com\/en/,
    marker: /Parcel tracking/i,
    forwarding: { notFound: /The parcel with this number was not found/ } },
  { carrier: 'ctt', number: 'RL000000005PT',
    route: /^https:\/\/www\.ctt\.pt\/feapl_2\/app\/open\/objectSearch\/objectSearch\.jspx\?/,
    marker: /Seguir objeto/i },
  { carrier: 'correos-spain', number: 'PR000000000000000C',
    route: /^https:\/\/www\.correos\.es\/es\/es\/herramientas\/localizador\//,
    marker: /Localizador de envíos|No encontramos resultados/i },
  { carrier: 'canada-post', number: '0000000000000001',
    route: /^https:\/\/www\.canadapost-postescanada\.ca\/track-reperage\/en/,
    marker: /Track results|Track/ },
  { carrier: 'india-post', number: 'EE000000000IN',
    route: /^https:\/\/myspeedpost\.com\/track\?/,
    marker: /consignment|speed post tracking/i },
  { carrier: 'pos-malaysia', number: 'MYPM00000000099',
    route: /^https:\/\/tracking\.pos\.com\.my\/tracking\//,
    marker: /TRACK MY PARCEL|Parcel Tracking/i },
  { carrier: 'spring-gds', number: 'LT000000000NL',
    route: /^https:\/\/postnl\.post\/track\?/,
    marker: /tracking numbers|track your parcels/i },
  { carrier: 'sunyou', number: 'SY00000000000',
    route: /^https:\/\/sypost\.net\/search\?/,
    marker: /Track Number|Not Found/ },
  { carrier: 'aliexpress', number: 'LP00000000000000',
    route: /^https:\/\/global\.cainiao\.com\/detail\.htm\?/,
    marker: /Track|Suivre/ },
  { carrier: 'ems', number: 'EB000000005CN',
    route: /^https:\/\/items\.ems\.post\/api\/publicTracking\/track\?/,
    marker: /Public Tracking|no results found/i },
  { carrier: 'japan-post', number: 'CN000000005JP',
    route: /^https:\/\/trackings\.post\.japanpost\.jp\/services\/srv\/search\/direct\?/,
    marker: /Track & Trace|Your item was not found/i },
  { carrier: 'australia-post', number: '7T0000000000000000001',
    route: /^https:\/\/auspost\.com\.au\/mypost\/track\/details\//,
    marker: /Australia Post|Track your item/i },
  { carrier: 'ekart', number: 'FMPP0000000001',
    route: /^https:\/\/ekartlogistics\.com\/ekartlogistics-web\/shipmenttrack\//,
    marker: /Track Your Order|No tracking data available for ID:/i },
  { carrier: 'xpressbees', number: '10000000000001',
    route: /^https:\/\/shipmentv2\.xpressbees\.com\/orders\/tracking\//,
    marker: /Enter an AWB number or Order ID to get live shipment updates|Tracking Error: Invalid Awb no/i },
  { carrier: 'nova-poshta', number: '59000000000001',
    route: /^https:\/\/novaposhta\.ua\/en\/tracking\/\d{14}\/?$/,
    marker: /Track your parcel|We have not found a parcel with this number/i },
  { carrier: 'spx-ph', number: 'PH000000000001',
    route: /^https:\/\/spx\.ph\/track\?/,
    marker: /Your search does not match any results/i },
  { carrier: 'speedpak', number: 'ES0000000000000UN0000000000N',
    route: /^https:\/\/www\.orangeconnex\.com\/tracking\/?$/,
    marker: /Shipment Tracking/i, forwarding: 'none' },
  { carrier: 'intelcom', number: 'INTLCM0000000000',
    route: /^https:\/\/dragonflyshipping\.ca\/en\/track-your-package\/(?:\?|$)/,
    marker: /The number you entered doesn't seem to match any of our current deliveries|Track another package/i,
    forwarding: { notFound: /The number you entered doesn't seem to match any of our current deliveries/i }, renderTimeoutMs: 20_000 },
  { carrier: 'jd-logistics', number: 'JD0000000000001',
    route: /^https:\/\/www\.jingdonglogistics\.com\/Tracking(?:\?|$)/,
    marker: /Track your shipment|Tracking your waybill/i },
  { carrier: 'dpd-de', number: '01000000000001',
    route: /^https:\/\/my\.dpd\.de\/myparcels\/dataprotection-tracking\.aspx(?:\?|$)/,
    marker: /Paketnummer|Leider können wir.*keine Daten zu Ihrem Paket/i },
  { carrier: 'dpd-uk', number: '00000000000001',
    route: /^https:\/\/track\.dpd\.co\.uk\/(?:\?|$)/,
    marker: /Enter the reference number and delivery postcode|Tracking Number, Calling card number/i },
  // The international tracker is a POST-only form, so the link cannot carry the number.
  { carrier: 'evri', number: 'H000000000000001',
    route: /^https:\/\/globaleco\.app\/track\/?$/,
    marker: /Search by tracking number/i, forwarding: 'none' },
];

/**
 * Carriers with their own adapter (or no automatic tracking) whose link no
 * case above opens, and why. Universal carriers are out of scope: their
 * tracking comes from shared providers, not the page the link opens.
 */
export const uncheckedTrackingLinks: Partial<Record<CarrierId, string>> = {
  'an-post': 'Radware Bot Manager sends automated sessions on www.anpost.com to validate.perfdrive.com and a CAPTCHA, so number forwarding cannot be verified',
  cne: 'the tracking portal redirects inspected Chrome sessions to about:blank through its anti-debug script, preventing a stable rendered-page check',
  'colis-prive': 'an unknown number-and-postcode credential redirects to the homepage, so only a real parcel verifies the link',
  dtdc: 'the MyDTDC Flutter page exposes no visible body text until accessibility is enabled, and the portal link opens its home page',
  'j-and-t': 'the Philippine page the link opens asks for a Tencent CAPTCHA before it looks a waybill up, and the adapter reads the Indonesian network instead',
  'j-and-t-cargo': 'headless Chrome receives the page frame without the tracking form, which a regular browser shows with the waybill filled in',
  'evri-uk': 'the protected key request rejects the default automated browser and leaves the domestic result panel empty, so number forwarding cannot be verified',
  'poste-italiane': 'the results page exposes no readable text to headless Chrome',
  'thailand-post': 'some of the tracker\'s servers stall on its script bundles, so the page often stays empty past the render window',
  sagawa: 'the inquiry page the link opens answers Access Denied while Sagawa keeps its inquiry service suspended after unauthorized access',
  usps: 'tools.usps.com answers automated Chrome with an anti-bot script instead of the page',
};
